import type { MessagesResponse } from "./types.js";

function contentBlocks(
  response: MessagesResponse,
): Array<{ type: string; [key: string]: unknown }> {
  return Array.isArray(response.content) ? response.content : [];
}

/**
 * Extract the `file_id`s of files generated by Skills during code execution.
 *
 * Generated files surface inside `bash_code_execution_tool_result` blocks:
 * `block.content` is a `bash_code_execution_result` whose `content` array holds
 * entries carrying a `file_id`. Download them via the Files API.
 */
export function extractFileIds(response: MessagesResponse): string[] {
  const fileIds: string[] = [];
  for (const block of contentBlocks(response)) {
    if (block.type !== "bash_code_execution_tool_result") continue;
    const inner = block.content as
      | { type?: string; content?: unknown }
      | undefined;
    if (!inner || inner.type !== "bash_code_execution_result") continue;
    if (!Array.isArray(inner.content)) continue;
    for (const entry of inner.content) {
      const fileId = (entry as { file_id?: unknown })?.file_id;
      if (typeof fileId === "string" && fileId) {
        fileIds.push(fileId);
      }
    }
  }
  return fileIds;
}

/** The container id assigned to (or reused by) a response, if any. */
export function getContainerId(response: MessagesResponse): string | undefined {
  return response.container?.id;
}

/** Concatenate the assistant's plain-text content blocks. */
export function getResponseText(response: MessagesResponse): string {
  return contentBlocks(response)
    .filter((block) => block.type === "text" && typeof block.text === "string")
    .map((block) => block.text as string)
    .join("");
}
